import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";
import 'aos/dist/aos.css'
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";

import Footer from "@/components/Footer";
const bric = Bricolage_Grotesque({ subsets: ['latin'], weight: ["200", "300", "400", "500", "600", "700", "800"] })



const kaftan = localFont({
  src: "./fonts/kaftan.otf",
  variable: "--kaftan",
  weight: "100 200 300 400 500 600 700 800 900"
})


export const metadata: Metadata = {
  title: "Tatsat Yoga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bric.className} ${kaftan.variable} antialiased bg-[#EAE6E1]`}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
