import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "900", "800"] })


const kaftan = localFont({
  src:"./fonts/kaftan.otf",
  variable:"--kaftan",
  weight:"100 200 300 400 500 600 700 800 900"
})


export const metadata: Metadata = {
  title: "Tatsat Yoga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${kaftan.variable} antialiased`}
      >
        <Providers>
          {/* <Navbar /> */}
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
